name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_call:  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: us-east4-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCR_JSON_KEY }}
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t nasamadi/madi-parser-nlm:latest .

    - name: Tag Docker image
      run: |
        docker tag nasamadi/madi-parser-nlm:latest us-east4-docker.pkg.dev/hq-madi-dev-4ebd7d92/docker-images/madi-parsers-nlm:latest

    - name: Push Docker image to GCR
      run: |
        docker push us-east4-docker.pkg.dev/hq-madi-dev-4ebd7d92/docker-images/madi-parsers-nlm:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push nasamadi/madi-parser-nlm:latest